# Generated by Django 2.2.5 on 2019-09-02 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Email',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Name',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Password',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Surname',
            new_name='password',
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
