# Generated by Django 2.2.5 on 2019-09-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190902_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10000),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='active',
            field=models.TextField(default='y'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.TextField(null=True),
        ),
    ]
